language: go
go:
  - 1.5
  - tip
sudo: true
before_install:
  - travis_retry wget --no-check-certificate -O /dev/stdout http://www.aleksey.com/xmlsec/download/xmlsec1-1.2.20.tar.gz | tar xzv
  - cd xmlsec1-1.2.20 && ./configure && make && sudo make install && sudo ldconfig && cd ..
